### ISSUE TITLE
Image dataSource (and gallery endpoint) do not work with modern kettle.

### ISSUE THREAD

**Issue by the-t-in-rtf** [GPII/ul-api#11]
In working on #5, I noticed that the dataSource tests are failing.  This may be something to do with changes in recent versions of Kettle, or may simply require checking the options distribution to ensure the baseUrl is set correctly in the test fixtures.

**Comment by amb26** [comment]
Yes, this will likely be due to the change in options structures accepted by modern DataSources. The modern code is in Infusion core and expects the field "url" potentially accompanied by a set of broken-out fields - https://github.com/fluid-project/infusion/blob/main/src/framework/core/js/DataSource.js#L373

**Comment by the-t-in-rtf** [comment]
It may also be that my options are messed up, before I had to stop I noticed these options:

```
    "auth": null,
    "host": null,
    "hostname": null,
    "path": "undefined/known-id",
    "url": "http:undefined/known-id",
```

Since I populate `url` using an expander and string template, the value I refer to may not have been passed in.

**Comment by the-t-in-rtf** [comment]
There was a bad/missing grade that resulted in the url not being populated with a protocol and hostname.  Once that was fixed, the dataSource tests worked as intended.
